kind: Secret 
apiVersion: v1
metadata:
  name: "kafka-secret-{{ include "deepfence-console.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
type: Opaque
data:
  kafka_brokers:  {{ default "deepfence-kafka-broker.{{ .Release.Namespace }}.svc:9092" .Values.db.kafka.broker | b64enc }}
  kafka_storageUUID: {{ default "" .Values.db.kafka.storageUUID | b64enc }}
  kafka_rest_proxy: {{ default "deepfence-rest-proxy.{{ .Release.Namespace }}.svc:8082" .Values.db.kafka_rest | b64enc }}

